package com.kwmax.up.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kwmax.up.model.DiaryReview;
import com.kwmax.up.model.EncourageSentence;
import com.kwmax.up.model.ImportDate;
import com.kwmax.up.model.ScheduleTodo;
import com.kwmax.up.model.Target;
import com.kwmax.up.model.TomatoTodo;
import com.kwmax.up.model.UpTemplet;
import com.kwmax.up.model.User;

import com.kwmax.up.dao.DiaryReviewDao;
import com.kwmax.up.dao.EncourageSentenceDao;
import com.kwmax.up.dao.ImportDateDao;
import com.kwmax.up.dao.ScheduleTodoDao;
import com.kwmax.up.dao.TargetDao;
import com.kwmax.up.dao.TomatoTodoDao;
import com.kwmax.up.dao.UpTempletDao;
import com.kwmax.up.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig diaryReviewDaoConfig;
    private final DaoConfig encourageSentenceDaoConfig;
    private final DaoConfig importDateDaoConfig;
    private final DaoConfig scheduleTodoDaoConfig;
    private final DaoConfig targetDaoConfig;
    private final DaoConfig tomatoTodoDaoConfig;
    private final DaoConfig upTempletDaoConfig;
    private final DaoConfig userDaoConfig;

    private final DiaryReviewDao diaryReviewDao;
    private final EncourageSentenceDao encourageSentenceDao;
    private final ImportDateDao importDateDao;
    private final ScheduleTodoDao scheduleTodoDao;
    private final TargetDao targetDao;
    private final TomatoTodoDao tomatoTodoDao;
    private final UpTempletDao upTempletDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        diaryReviewDaoConfig = daoConfigMap.get(DiaryReviewDao.class).clone();
        diaryReviewDaoConfig.initIdentityScope(type);

        encourageSentenceDaoConfig = daoConfigMap.get(EncourageSentenceDao.class).clone();
        encourageSentenceDaoConfig.initIdentityScope(type);

        importDateDaoConfig = daoConfigMap.get(ImportDateDao.class).clone();
        importDateDaoConfig.initIdentityScope(type);

        scheduleTodoDaoConfig = daoConfigMap.get(ScheduleTodoDao.class).clone();
        scheduleTodoDaoConfig.initIdentityScope(type);

        targetDaoConfig = daoConfigMap.get(TargetDao.class).clone();
        targetDaoConfig.initIdentityScope(type);

        tomatoTodoDaoConfig = daoConfigMap.get(TomatoTodoDao.class).clone();
        tomatoTodoDaoConfig.initIdentityScope(type);

        upTempletDaoConfig = daoConfigMap.get(UpTempletDao.class).clone();
        upTempletDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        diaryReviewDao = new DiaryReviewDao(diaryReviewDaoConfig, this);
        encourageSentenceDao = new EncourageSentenceDao(encourageSentenceDaoConfig, this);
        importDateDao = new ImportDateDao(importDateDaoConfig, this);
        scheduleTodoDao = new ScheduleTodoDao(scheduleTodoDaoConfig, this);
        targetDao = new TargetDao(targetDaoConfig, this);
        tomatoTodoDao = new TomatoTodoDao(tomatoTodoDaoConfig, this);
        upTempletDao = new UpTempletDao(upTempletDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(DiaryReview.class, diaryReviewDao);
        registerDao(EncourageSentence.class, encourageSentenceDao);
        registerDao(ImportDate.class, importDateDao);
        registerDao(ScheduleTodo.class, scheduleTodoDao);
        registerDao(Target.class, targetDao);
        registerDao(TomatoTodo.class, tomatoTodoDao);
        registerDao(UpTemplet.class, upTempletDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        diaryReviewDaoConfig.clearIdentityScope();
        encourageSentenceDaoConfig.clearIdentityScope();
        importDateDaoConfig.clearIdentityScope();
        scheduleTodoDaoConfig.clearIdentityScope();
        targetDaoConfig.clearIdentityScope();
        tomatoTodoDaoConfig.clearIdentityScope();
        upTempletDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public DiaryReviewDao getDiaryReviewDao() {
        return diaryReviewDao;
    }

    public EncourageSentenceDao getEncourageSentenceDao() {
        return encourageSentenceDao;
    }

    public ImportDateDao getImportDateDao() {
        return importDateDao;
    }

    public ScheduleTodoDao getScheduleTodoDao() {
        return scheduleTodoDao;
    }

    public TargetDao getTargetDao() {
        return targetDao;
    }

    public TomatoTodoDao getTomatoTodoDao() {
        return tomatoTodoDao;
    }

    public UpTempletDao getUpTempletDao() {
        return upTempletDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
