package com.kwmax.up.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.kwmax.up.model.DiaryReview;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DIARY_REVIEW".
*/
public class DiaryReviewDao extends AbstractDao<DiaryReview, Long> {

    public static final String TABLENAME = "DIARY_REVIEW";

    /**
     * Properties of entity DiaryReview.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Userid = new Property(1, String.class, "userid", false, "USERID");
        public final static Property Date = new Property(2, String.class, "date", false, "DATE");
        public final static Property Updatetime = new Property(3, String.class, "updatetime", false, "UPDATETIME");
        public final static Property Name = new Property(4, String.class, "name", false, "NAME");
        public final static Property Content = new Property(5, String.class, "content", false, "CONTENT");
        public final static Property LastEdittime = new Property(6, String.class, "lastEdittime", false, "LAST_EDITTIME");
        public final static Property Done = new Property(7, String.class, "done", false, "DONE");
    }


    public DiaryReviewDao(DaoConfig config) {
        super(config);
    }
    
    public DiaryReviewDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DIARY_REVIEW\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USERID\" TEXT," + // 1: userid
                "\"DATE\" TEXT," + // 2: date
                "\"UPDATETIME\" TEXT," + // 3: updatetime
                "\"NAME\" TEXT," + // 4: name
                "\"CONTENT\" TEXT," + // 5: content
                "\"LAST_EDITTIME\" TEXT," + // 6: lastEdittime
                "\"DONE\" TEXT);"); // 7: done
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DIARY_REVIEW\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DiaryReview entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userid = entity.getUserid();
        if (userid != null) {
            stmt.bindString(2, userid);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(3, date);
        }
 
        String updatetime = entity.getUpdatetime();
        if (updatetime != null) {
            stmt.bindString(4, updatetime);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(6, content);
        }
 
        String lastEdittime = entity.getLastEdittime();
        if (lastEdittime != null) {
            stmt.bindString(7, lastEdittime);
        }
 
        String done = entity.getDone();
        if (done != null) {
            stmt.bindString(8, done);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DiaryReview entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userid = entity.getUserid();
        if (userid != null) {
            stmt.bindString(2, userid);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(3, date);
        }
 
        String updatetime = entity.getUpdatetime();
        if (updatetime != null) {
            stmt.bindString(4, updatetime);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(6, content);
        }
 
        String lastEdittime = entity.getLastEdittime();
        if (lastEdittime != null) {
            stmt.bindString(7, lastEdittime);
        }
 
        String done = entity.getDone();
        if (done != null) {
            stmt.bindString(8, done);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DiaryReview readEntity(Cursor cursor, int offset) {
        DiaryReview entity = new DiaryReview( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // date
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // updatetime
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // name
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // content
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // lastEdittime
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // done
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DiaryReview entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDate(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUpdatetime(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setContent(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setLastEdittime(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setDone(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DiaryReview entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DiaryReview entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DiaryReview entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
